version: '3.7'

services:
  test-db:
    image: mysql:latest
    container_name: test-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - my-test-db:/var/lib/mysql

  test-redis:
    image: redis:latest
    container_name: test-redis
    expose:
      - "6379"
    ports:
      - "6379:6379"

volumes:
  my-test-db: